<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HealthScan.Application\HealthScan.Application.csproj" />
    <ProjectReference Include="..\HealthScan.Infrastructure\HealthScan.Infrastructure.csproj" />
  </ItemGroup>

</Project>
