// <auto-generated />
using System;
using System.Collections.Generic;
using HealthScan.Domain.Entities.OpenFoodFacts;
using HealthScan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthScan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260117092742_AddOpenFoodFactsTables")]
    partial class AddOpenFoodFactsTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthScan.Domain.Entities.IngredientFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionHe")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_he");

                    b.Property<string>("FlagType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("flag_type");

                    b.Property<string>("IngredientPattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ingredient_pattern");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("PenaltyPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("penalty_points");

                    b.HasKey("Id");

                    b.HasIndex("FlagType");

                    b.ToTable("ingredient_flags", (string)null);
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffEnvironment", b =>
                {
                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<decimal?>("AgribalyseCo2Agriculture")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("agribalyse_co2_agriculture");

                    b.Property<decimal?>("AgribalyseCo2Consumption")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("agribalyse_co2_consumption");

                    b.Property<decimal?>("AgribalyseCo2Distribution")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("agribalyse_co2_distribution");

                    b.Property<decimal?>("AgribalyseCo2Packaging")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("agribalyse_co2_packaging");

                    b.Property<decimal?>("AgribalyseCo2Processing")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("agribalyse_co2_processing");

                    b.Property<decimal?>("AgribalyseCo2Total")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("agribalyse_co2_total");

                    b.Property<decimal?>("AgribalyseCo2Transportation")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("agribalyse_co2_transportation");

                    b.Property<decimal?>("AgribalyseEfSingleScore")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("agribalyse_ef_single_score");

                    b.Property<int?>("AgribalyseFoodCode")
                        .HasColumnType("integer")
                        .HasColumnName("agribalyse_food_code");

                    b.Property<string>("AgribalyseFoodName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("agribalyse_food_name");

                    b.Property<decimal?>("CarbonFootprint100g")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("carbon_footprint_100g");

                    b.Property<decimal?>("CarbonFootprintServing")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("carbon_footprint_serving");

                    b.Property<string>("CarbonFootprintSource")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("carbon_footprint_source");

                    b.Property<string>("CarbonFootprintUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("carbon_footprint_unit");

                    b.Property<decimal?>("EnvironmentImpactLevel")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("environment_impact_level");

                    b.PrimitiveCollection<string>("EnvironmentImpactLevelTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("environment_impact_level_tags");

                    b.Property<decimal?>("ForestFootprint")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("forest_footprint");

                    b.Property<bool?>("IsForestFootprintFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_forest_footprint_free");

                    b.Property<DateTime>("LastSyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ManufacturingPlaces")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("manufacturing_places");

                    b.PrimitiveCollection<string>("ManufacturingPlacesTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("manufacturing_places_tags");

                    b.Property<string>("Origins")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("origins");

                    b.PrimitiveCollection<string>("OriginsTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("origins_tags");

                    b.Property<List<OffPackagingComponent>>("PackagingComponents")
                        .HasColumnType("jsonb")
                        .HasColumnName("packaging_components");

                    b.Property<string>("PackagingMaterials")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("packaging_materials");

                    b.PrimitiveCollection<string>("PackagingMaterialsTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("packaging_materials_tags");

                    b.Property<string>("PackagingRecycling")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("packaging_recycling");

                    b.Property<string>("RecyclingInstruction")
                        .HasColumnType("text")
                        .HasColumnName("recycling_instruction");

                    b.Property<string>("RecyclingInstructionToDiscard")
                        .HasColumnType("text")
                        .HasColumnName("recycling_instruction_to_discard");

                    b.Property<string>("RecyclingInstructionToRecycle")
                        .HasColumnType("text")
                        .HasColumnName("recycling_instruction_to_recycle");

                    b.Property<decimal?>("WaterFootprint100g")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("water_footprint_100g");

                    b.Property<string>("WaterFootprintUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("water_footprint_unit");

                    b.HasKey("Barcode");

                    b.HasIndex("CarbonFootprint100g");

                    b.ToTable("off_environment", (string)null);
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffImages", b =>
                {
                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("ImageFrontSmallUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_front_small_url");

                    b.Property<string>("ImageFrontThumbUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_front_thumb_url");

                    b.Property<string>("ImageFrontUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_front_url");

                    b.Property<string>("ImageIngredientsSmallUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_ingredients_small_url");

                    b.Property<string>("ImageIngredientsThumbUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_ingredients_thumb_url");

                    b.Property<string>("ImageIngredientsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_ingredients_url");

                    b.Property<string>("ImageNutritionSmallUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_nutrition_small_url");

                    b.Property<string>("ImageNutritionThumbUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_nutrition_thumb_url");

                    b.Property<string>("ImageNutritionUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_nutrition_url");

                    b.Property<string>("ImagePackagingSmallUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_packaging_small_url");

                    b.Property<string>("ImagePackagingThumbUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_packaging_thumb_url");

                    b.Property<string>("ImagePackagingUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_packaging_url");

                    b.Property<string>("ImageSmallUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_small_url");

                    b.Property<string>("ImageThumbUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_thumb_url");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<int?>("ImagesCount")
                        .HasColumnType("integer")
                        .HasColumnName("images_count");

                    b.PrimitiveCollection<string>("ImagesKeys")
                        .HasColumnType("jsonb")
                        .HasColumnName("images_keys");

                    b.Property<DateTime>("LastSyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<List<OffImageMetadata>>("SelectedImages")
                        .HasColumnType("jsonb")
                        .HasColumnName("selected_images");

                    b.HasKey("Barcode");

                    b.ToTable("off_images", (string)null);
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffIngredients", b =>
                {
                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.PrimitiveCollection<string>("Additives")
                        .HasColumnType("jsonb")
                        .HasColumnName("additives");

                    b.Property<int?>("AdditivesCount")
                        .HasColumnType("integer")
                        .HasColumnName("additives_count");

                    b.PrimitiveCollection<string>("AdditivesTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("additives_tags");

                    b.PrimitiveCollection<string>("Allergens")
                        .HasColumnType("jsonb")
                        .HasColumnName("allergens");

                    b.Property<string>("AllergensHierarchy")
                        .HasColumnType("text")
                        .HasColumnName("allergens_hierarchy");

                    b.PrimitiveCollection<string>("AllergensTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("allergens_tags");

                    b.PrimitiveCollection<string>("AminoAcidsTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("amino_acids_tags");

                    b.Property<string>("IngredientsAnalysis")
                        .HasColumnType("text")
                        .HasColumnName("ingredients_analysis");

                    b.PrimitiveCollection<string>("IngredientsAnalysisTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("ingredients_analysis_tags");

                    b.Property<int?>("IngredientsCount")
                        .HasColumnType("integer")
                        .HasColumnName("ingredients_count");

                    b.Property<List<OffIngredientItem>>("IngredientsParsed")
                        .HasColumnType("jsonb")
                        .HasColumnName("ingredients_parsed");

                    b.Property<decimal?>("IngredientsPercentAnalysis")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("ingredients_percent_analysis");

                    b.Property<string>("IngredientsText")
                        .HasColumnType("text")
                        .HasColumnName("ingredients_text");

                    b.Property<string>("IngredientsTextEn")
                        .HasColumnType("text")
                        .HasColumnName("ingredients_text_en");

                    b.Property<string>("IngredientsTextHe")
                        .HasColumnType("text")
                        .HasColumnName("ingredients_text_he");

                    b.Property<bool?>("IsPalmOilFree")
                        .HasColumnType("boolean")
                        .HasColumnName("is_palm_oil_free");

                    b.Property<bool?>("IsVegan")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vegan");

                    b.Property<bool?>("IsVegetarian")
                        .HasColumnType("boolean")
                        .HasColumnName("is_vegetarian");

                    b.Property<DateTime>("LastSyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at")
                        .HasDefaultValueSql("NOW()");

                    b.PrimitiveCollection<string>("MineralsTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("minerals_tags");

                    b.Property<int?>("NovaGroup")
                        .HasColumnType("integer")
                        .HasColumnName("nova_group");

                    b.Property<string>("NovaGroupsMarkers")
                        .HasColumnType("text")
                        .HasColumnName("nova_groups_markers");

                    b.PrimitiveCollection<string>("NovaGroupsTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("nova_groups_tags");

                    b.PrimitiveCollection<string>("NucleotidesTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("nucleotides_tags");

                    b.PrimitiveCollection<string>("OtherNutritionalSubstancesTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("other_nutritional_substances_tags");

                    b.PrimitiveCollection<string>("Traces")
                        .HasColumnType("jsonb")
                        .HasColumnName("traces");

                    b.PrimitiveCollection<string>("TracesTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("traces_tags");

                    b.Property<string>("VeganAnalysis")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vegan_analysis");

                    b.Property<string>("VegetarianAnalysis")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vegetarian_analysis");

                    b.PrimitiveCollection<string>("VitaminsTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("vitamins_tags");

                    b.HasKey("Barcode");

                    b.HasIndex("IsVegan");

                    b.HasIndex("IsVegetarian");

                    b.HasIndex("NovaGroup");

                    b.ToTable("off_ingredients", (string)null);
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffNutrition", b =>
                {
                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<decimal?>("Alcohol100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("alcohol_100g");

                    b.Property<decimal?>("Caffeine100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("caffeine_100g");

                    b.Property<decimal?>("Calcium100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("calcium_100g");

                    b.Property<decimal?>("Carbohydrates100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("carbohydrates_100g");

                    b.Property<decimal?>("CarbohydratesServing")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("carbohydrates_serving");

                    b.Property<decimal?>("Cholesterol100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("cholesterol_100g");

                    b.Property<decimal?>("Copper100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("copper_100g");

                    b.Property<decimal?>("EnergyKcal100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("energy_kcal_100g");

                    b.Property<decimal?>("EnergyKcalServing")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("energy_kcal_serving");

                    b.Property<decimal?>("EnergyKj100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("energy_kj_100g");

                    b.Property<decimal?>("EnergyKjServing")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("energy_kj_serving");

                    b.Property<decimal?>("Fat100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("fat_100g");

                    b.Property<decimal?>("FatServing")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("fat_serving");

                    b.Property<decimal?>("Fiber100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("fiber_100g");

                    b.Property<decimal?>("FiberServing")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("fiber_serving");

                    b.Property<decimal?>("Fluoride100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("fluoride_100g");

                    b.Property<decimal?>("Iodine100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("iodine_100g");

                    b.Property<decimal?>("Iron100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("iron_100g");

                    b.Property<DateTime>("LastSyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("Magnesium100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("magnesium_100g");

                    b.Property<decimal?>("Manganese100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("manganese_100g");

                    b.Property<decimal?>("MonounsaturatedFat100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("monounsaturated_fat_100g");

                    b.Property<string>("NutritionDataPer")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nutrition_data_per");

                    b.Property<string>("NutritionGradeFr")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("nutrition_grade_fr");

                    b.Property<decimal?>("Omega3Fat100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("omega3_fat_100g");

                    b.Property<decimal?>("Omega6Fat100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("omega6_fat_100g");

                    b.Property<decimal?>("Phosphorus100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("phosphorus_100g");

                    b.Property<decimal?>("Polyols100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("polyols_100g");

                    b.Property<decimal?>("PolyunsaturatedFat100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("polyunsaturated_fat_100g");

                    b.Property<decimal?>("Potassium100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("potassium_100g");

                    b.Property<decimal?>("Proteins100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("proteins_100g");

                    b.Property<decimal?>("ProteinsServing")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("proteins_serving");

                    b.Property<decimal?>("Salt100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("salt_100g");

                    b.Property<decimal?>("SaltServing")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("salt_serving");

                    b.Property<decimal?>("SaturatedFat100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("saturated_fat_100g");

                    b.Property<decimal?>("SaturatedFatServing")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("saturated_fat_serving");

                    b.Property<decimal?>("Selenium100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("selenium_100g");

                    b.Property<decimal?>("Sodium100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("sodium_100g");

                    b.Property<decimal?>("SodiumServing")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("sodium_serving");

                    b.Property<decimal?>("Starch100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("starch_100g");

                    b.Property<decimal?>("Sugars100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("sugars_100g");

                    b.Property<decimal?>("SugarsServing")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("sugars_serving");

                    b.Property<decimal?>("Taurine100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("taurine_100g");

                    b.Property<decimal?>("TransFat100g")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("trans_fat_100g");

                    b.Property<decimal?>("VitaminA100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("vitamin_a_100g");

                    b.Property<decimal?>("VitaminB1100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("vitamin_b1_100g");

                    b.Property<decimal?>("VitaminB12100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("vitamin_b12_100g");

                    b.Property<decimal?>("VitaminB2100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("vitamin_b2_100g");

                    b.Property<decimal?>("VitaminB6100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("vitamin_b6_100g");

                    b.Property<decimal?>("VitaminB9100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("vitamin_b9_100g");

                    b.Property<decimal?>("VitaminC100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("vitamin_c_100g");

                    b.Property<decimal?>("VitaminD100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("vitamin_d_100g");

                    b.Property<decimal?>("VitaminE100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("vitamin_e_100g");

                    b.Property<decimal?>("VitaminK100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("vitamin_k_100g");

                    b.Property<decimal?>("VitaminPp100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("vitamin_pp_100g");

                    b.Property<decimal?>("Zinc100g")
                        .HasPrecision(12, 6)
                        .HasColumnType("numeric(12,6)")
                        .HasColumnName("zinc_100g");

                    b.HasKey("Barcode");

                    b.ToTable("off_nutrition", (string)null);
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffProduct", b =>
                {
                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("Brands")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("brands");

                    b.Property<string>("BrandsTags")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("brands_tags");

                    b.Property<string>("Categories")
                        .HasColumnType("text")
                        .HasColumnName("categories");

                    b.Property<string>("CategoriesHierarchy")
                        .HasColumnType("text")
                        .HasColumnName("categories_hierarchy");

                    b.PrimitiveCollection<string>("CategoriesTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("categories_tags");

                    b.Property<decimal?>("Completeness")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("completeness");

                    b.Property<string>("Countries")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("countries");

                    b.PrimitiveCollection<string>("CountriesTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("countries_tags");

                    b.Property<DateTime?>("CreatedT")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_t");

                    b.Property<string>("Creator")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("creator");

                    b.Property<string>("Editor")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("editor");

                    b.Property<int?>("EditorsCount")
                        .HasColumnType("integer")
                        .HasColumnName("editors_count");

                    b.Property<string>("GenericName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("generic_name");

                    b.Property<string>("GenericNameEn")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("generic_name_en");

                    b.Property<string>("GenericNameHe")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("generic_name_he");

                    b.Property<DateTime>("ImportedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Labels")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("labels");

                    b.PrimitiveCollection<string>("LabelsTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("labels_tags");

                    b.Property<DateTime?>("LastModifiedT")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified_t");

                    b.Property<DateTime>("LastSyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ManufacturingPlaces")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("manufacturing_places");

                    b.Property<string>("Origins")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("origins");

                    b.Property<string>("Packaging")
                        .HasColumnType("text")
                        .HasColumnName("packaging");

                    b.PrimitiveCollection<string>("PackagingTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("packaging_tags");

                    b.Property<string>("ProductName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductNameEn")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("product_name_en");

                    b.Property<string>("ProductNameHe")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("product_name_he");

                    b.Property<string>("Quantity")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("quantity");

                    b.Property<decimal?>("ServingQuantity")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("serving_quantity");

                    b.Property<string>("ServingSize")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("serving_size");

                    b.Property<string>("States")
                        .HasColumnType("text")
                        .HasColumnName("states");

                    b.PrimitiveCollection<string>("StatesTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("states_tags");

                    b.Property<string>("Stores")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("stores");

                    b.HasKey("Barcode");

                    b.HasIndex("Brands");

                    b.HasIndex("Completeness");

                    b.HasIndex("LastSyncedAt");

                    b.ToTable("off_products", (string)null);
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffScores", b =>
                {
                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<int?>("DataQualityErrorsCount")
                        .HasColumnType("integer")
                        .HasColumnName("data_quality_errors_count");

                    b.PrimitiveCollection<string>("DataQualityErrorsTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_quality_errors_tags");

                    b.Property<int?>("DataQualityInfoCount")
                        .HasColumnType("integer")
                        .HasColumnName("data_quality_info_count");

                    b.PrimitiveCollection<string>("DataQualityInfoTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_quality_info_tags");

                    b.Property<int?>("DataQualityWarningsCount")
                        .HasColumnType("integer")
                        .HasColumnName("data_quality_warnings_count");

                    b.PrimitiveCollection<string>("DataQualityWarningsTags")
                        .HasColumnType("jsonb")
                        .HasColumnName("data_quality_warnings_tags");

                    b.Property<int?>("EcoScoreAdjustments")
                        .HasColumnType("integer")
                        .HasColumnName("eco_score_adjustments");

                    b.Property<string>("EcoScoreGrade")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("eco_score_grade");

                    b.Property<int?>("EcoScoreOrigins")
                        .HasColumnType("integer")
                        .HasColumnName("eco_score_origins");

                    b.Property<int?>("EcoScorePackaging")
                        .HasColumnType("integer")
                        .HasColumnName("eco_score_packaging");

                    b.Property<int?>("EcoScoreProduction")
                        .HasColumnType("integer")
                        .HasColumnName("eco_score_production");

                    b.Property<int?>("EcoScoreScore")
                        .HasColumnType("integer")
                        .HasColumnName("eco_score_score");

                    b.Property<int?>("EcoScoreThreatenedSpecies")
                        .HasColumnType("integer")
                        .HasColumnName("eco_score_threatened_species");

                    b.Property<string>("EcoScoreVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("eco_score_version");

                    b.Property<decimal?>("KnownNutrientsCount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("known_nutrients_count");

                    b.Property<DateTime>("LastSyncedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("NovaGroup")
                        .HasColumnType("integer")
                        .HasColumnName("nova_group");

                    b.Property<string>("NutriScoreGrade")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nutri_score_grade");

                    b.Property<int?>("NutriScoreScore")
                        .HasColumnType("integer")
                        .HasColumnName("nutri_score_score");

                    b.Property<string>("NutriScoreVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nutri_score_version");

                    b.Property<decimal?>("NutrientLevelsEnergy")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("nutrient_levels_energy");

                    b.Property<string>("NutrientLevelsFat")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nutrient_levels_fat");

                    b.Property<string>("NutrientLevelsSalt")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nutrient_levels_salt");

                    b.Property<string>("NutrientLevelsSaturatedFat")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nutrient_levels_saturated_fat");

                    b.Property<string>("NutrientLevelsSugars")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nutrient_levels_sugars");

                    b.Property<string>("NutriscoreGrade2021")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nutriscore_grade_2021");

                    b.Property<string>("NutriscoreGrade2023")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nutriscore_grade_2023");

                    b.Property<int?>("NutriscoreNegativePoints2021")
                        .HasColumnType("integer")
                        .HasColumnName("nutriscore_negative_points_2021");

                    b.Property<int?>("NutriscoreNegativePoints2023")
                        .HasColumnType("integer")
                        .HasColumnName("nutriscore_negative_points_2023");

                    b.Property<int?>("NutriscorePositivePoints2021")
                        .HasColumnType("integer")
                        .HasColumnName("nutriscore_positive_points_2021");

                    b.Property<int?>("NutriscorePositivePoints2023")
                        .HasColumnType("integer")
                        .HasColumnName("nutriscore_positive_points_2023");

                    b.Property<int?>("NutriscoreScore2021")
                        .HasColumnType("integer")
                        .HasColumnName("nutriscore_score_2021");

                    b.Property<int?>("NutriscoreScore2023")
                        .HasColumnType("integer")
                        .HasColumnName("nutriscore_score_2023");

                    b.Property<decimal?>("UnknownNutrientsCount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unknown_nutrients_count");

                    b.HasKey("Barcode");

                    b.HasIndex("EcoScoreGrade");

                    b.HasIndex("NovaGroup");

                    b.HasIndex("NutriScoreGrade");

                    b.ToTable("off_scores", (string)null);
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string>("Allergens")
                        .HasColumnType("jsonb")
                        .HasColumnName("allergens");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("barcode");

                    b.Property<string>("Brand")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("brand");

                    b.Property<decimal?>("Carbohydrates100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carbohydrates_100g");

                    b.Property<decimal?>("CarbohydratesServing")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("carbohydrates_serving");

                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal?>("Energy100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("energy_100g");

                    b.Property<decimal?>("EnergyServing")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("energy_serving");

                    b.Property<decimal?>("Fat100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fat_100g");

                    b.Property<decimal?>("FatServing")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fat_serving");

                    b.Property<decimal?>("Fiber100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fiber_100g");

                    b.Property<decimal?>("FiberServing")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("fiber_serving");

                    b.Property<string>("ImageFrontUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_front_url");

                    b.Property<string>("ImageIngredientsUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_ingredients_url");

                    b.Property<string>("ImageNutritionUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_nutrition_url");

                    b.PrimitiveCollection<string>("IngredientsParsed")
                        .HasColumnType("jsonb")
                        .HasColumnName("ingredients_parsed");

                    b.Property<string>("IngredientsTextEn")
                        .HasColumnType("text")
                        .HasColumnName("ingredients_text_en");

                    b.Property<string>("IngredientsTextHe")
                        .HasColumnType("text")
                        .HasColumnName("ingredients_text_he");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("NameEn")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameHe")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name_he");

                    b.Property<bool>("NutritionComplete")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("nutrition_complete");

                    b.Property<string>("OffBarcode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("off_barcode");

                    b.Property<DateTime?>("OffSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("off_synced_at");

                    b.Property<string>("PackageSize")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("package_size");

                    b.Property<decimal?>("Protein100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("protein_100g");

                    b.Property<decimal?>("ProteinServing")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("protein_serving");

                    b.Property<decimal?>("SaturatedFat100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saturated_fat_100g");

                    b.Property<decimal?>("SaturatedFatServing")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("saturated_fat_serving");

                    b.Property<string>("ServingSize")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serving_size");

                    b.Property<decimal?>("Sodium100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sodium_100g");

                    b.Property<decimal?>("SodiumServing")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sodium_serving");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("user")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<decimal?>("Sugars100g")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sugars_100g");

                    b.Property<decimal?>("SugarsServing")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("sugars_serving");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("OffBarcode");

                    b.HasIndex("Status");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.ProductContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("barcode");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("field_name");

                    b.Property<string>("FieldValue")
                        .HasColumnType("text")
                        .HasColumnName("field_value");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("ProductId");

                    b.HasIndex("Status");

                    b.ToTable("product_contributions", (string)null);
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.ScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("barcode");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("device_id");

                    b.Property<string>("Grade")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("grade");

                    b.Property<string>("ScanType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scan_type");

                    b.Property<DateTime>("ScannedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.HasIndex("Barcode");

                    b.HasIndex("ScannedAt");

                    b.ToTable("scan_events", (string)null);
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.ScoringRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConditionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("condition_json");

                    b.Property<string>("DescriptionEn")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_en");

                    b.Property<string>("DescriptionHe")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description_he");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("rule_name");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("rule_type");

                    b.HasKey("Id");

                    b.HasIndex("RuleName")
                        .IsUnique();

                    b.ToTable("scoring_rules", (string)null);
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffEnvironment", b =>
                {
                    b.HasOne("HealthScan.Domain.Entities.OpenFoodFacts.OffProduct", "Product")
                        .WithOne("Environment")
                        .HasForeignKey("HealthScan.Domain.Entities.OpenFoodFacts.OffEnvironment", "Barcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffImages", b =>
                {
                    b.HasOne("HealthScan.Domain.Entities.OpenFoodFacts.OffProduct", "Product")
                        .WithOne("Images")
                        .HasForeignKey("HealthScan.Domain.Entities.OpenFoodFacts.OffImages", "Barcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffIngredients", b =>
                {
                    b.HasOne("HealthScan.Domain.Entities.OpenFoodFacts.OffProduct", "Product")
                        .WithOne("Ingredients")
                        .HasForeignKey("HealthScan.Domain.Entities.OpenFoodFacts.OffIngredients", "Barcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffNutrition", b =>
                {
                    b.HasOne("HealthScan.Domain.Entities.OpenFoodFacts.OffProduct", "Product")
                        .WithOne("Nutrition")
                        .HasForeignKey("HealthScan.Domain.Entities.OpenFoodFacts.OffNutrition", "Barcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffScores", b =>
                {
                    b.HasOne("HealthScan.Domain.Entities.OpenFoodFacts.OffProduct", "Product")
                        .WithOne("Scores")
                        .HasForeignKey("HealthScan.Domain.Entities.OpenFoodFacts.OffScores", "Barcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.ProductContribution", b =>
                {
                    b.HasOne("HealthScan.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HealthScan.Domain.Entities.OpenFoodFacts.OffProduct", b =>
                {
                    b.Navigation("Environment");

                    b.Navigation("Images");

                    b.Navigation("Ingredients");

                    b.Navigation("Nutrition");

                    b.Navigation("Scores");
                });
#pragma warning restore 612, 618
        }
    }
}
